catalyst_center_version: 2.3.7.6
network_settings_details:
- network_management_details:
  - site_name: Global/USA
    settings:
      message_of_the_day:
        banner_message: These devices are for testing purposes only
        retain_existing_banner: false
      wired_data_collection:
        enable_wired_data_collection: true
      wireless_telemetry:
        enable_wireless_telemetry: true
