catalyst_center_version: 2.3.7.6
network_settings_details:
- reserve_pool_details:
  - ipv6_address_space: false
    ipv4_global_pool: 204.1.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 204.1.1.0
    ipv4_gateway: 204.1.1.1
    name: underlay_linkpool_sjc
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: LAN
  - ipv6_address_space: false
    ipv4_global_pool: 204.1.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 204.1.2.0
    ipv4_gateway: 204.1.2.1
    name: underlay_lbpool_sjc
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: LAN
  - ipv6_address_space: false
    ipv4_global_pool: 204.1.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 204.1.3.0
    ipv4_gateway: 204.1.3.1
    name: underlay_linkpool_sf
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: LAN
  - ipv6_address_space: false
    ipv4_global_pool: 204.1.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 204.1.4.0
    ipv4_gateway: 204.1.4.1
    name: underlay_lbpool_sf
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: LAN
  - ipv6_address_space: false
    ipv4_global_pool: 204.3.0.0/20
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 204.3.0.0
    ipv4_gateway: 204.3.0.1
    name: APPOOL_SJC
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
  - ipv6_address_space: false
    ipv4_global_pool: 204.4.0.0/20
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 204.4.0.0
    ipv4_gateway: 204.4.0.1
    name: EXTPOOL_SJC
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
  - ipv6_address_space: false
    ipv4_global_pool: 204.3.0.0/20
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 204.3.1.0
    ipv4_gateway: 204.3.1.1
    name: APPOOL_SF
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
  - ipv6_address_space: false
    ipv4_global_pool: 204.4.0.0/20
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 204.4.1.0
    ipv4_gateway: 204.4.1.1
    name: EXTPOOL_SF
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
  - ipv6_address_space: true
    ipv4_global_pool: 192.168.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.168.0.0
    ipv4_gateway: 192.168.0.1
    ipv6_global_pool: 2004:192:168::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:168::1:0
    ipv6_gateway: 2004:192:168::1:1
    name: EMPLOYEEPOOL_sjc
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - ipv6_address_space: true
    ipv4_global_pool: 192.168.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.168.1.0
    ipv4_gateway: 192.168.1.1
    ipv6_global_pool: 2004:192:168::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:168::2:0
    ipv6_gateway: 2004:192:168::2:1
    name: EMPLOYEEPOOL_sf
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: GUESTPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.169.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.169.0.0
    ipv4_gateway: 192.169.0.1
    ipv6_global_pool: 2004:192:169::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:169::0
    ipv6_gateway: 2004:192:169::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: GUESTPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.169.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.169.1.0
    ipv4_gateway: 192.169.1.1
    ipv6_global_pool: 2004:192:169::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:169::1:0
    ipv6_gateway: 2004:192:169::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: IOTPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.170.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.170.0.0
    ipv4_gateway: 192.170.0.1
    ipv6_global_pool: 2004:192:170::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:170::0
    ipv6_gateway: 2004:192:170::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: IOTPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.170.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.170.1.0
    ipv4_gateway: 192.170.1.1
    ipv6_global_pool: 2004:192:170::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:170::1:0
    ipv6_gateway: 2004:192:170::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: MGMTPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.171.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.171.0.0
    ipv4_gateway: 192.171.0.1
    ipv6_global_pool: 2004:192:171::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:171::0
    ipv6_gateway: 2004:192:171::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: MGMTPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.171.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.171.1.0
    ipv4_gateway: 192.171.1.1
    ipv6_global_pool: 2004:192:171::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:171::1:0
    ipv6_gateway: 2004:192:171::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: VOICEPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.172.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.172.0.0
    ipv4_gateway: 192.172.0.1
    ipv6_global_pool: 2004:192:172::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:172::0
    ipv6_gateway: 2004:192:172::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: VOICEPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.172.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.172.1.0
    ipv4_gateway: 192.172.1.1
    ipv6_global_pool: 2004:192:172::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:172::1:0
    ipv6_gateway: 2004:192:172::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: CRITICALDATAPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.173.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.173.0.0
    ipv4_gateway: 192.173.0.1
    ipv6_global_pool: 2004:192:173::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:173::0
    ipv6_gateway: 2004:192:173::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: CRITICALDATAPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.173.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.173.1.0
    ipv4_gateway: 192.173.1.1
    ipv6_global_pool: 2004:192:173::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:173::1:0
    ipv6_gateway: 2004:192:173::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: CRITICALVOICEPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.174.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.174.0.0
    ipv4_gateway: 192.174.0.1
    ipv6_global_pool: 2004:192:174::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:174::0
    ipv6_gateway: 2004:192:174::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: CRITICALVOICEPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.174.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.174.1.0
    ipv4_gateway: 192.174.1.1
    ipv6_global_pool: 2004:192:174::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:174::1:0
    ipv6_gateway: 2004:192:174::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: MULTICASTPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.175.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.175.0.0
    ipv4_gateway: 192.175.0.1
    ipv6_global_pool: 2004:192:175::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:175::0
    ipv6_gateway: 2004:192:175::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
  - name: MULTICASTPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.175.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.175.1.0
    ipv4_gateway: 192.175.1.1
    ipv6_global_pool: 2004:192:175::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:175::1:0
    ipv6_gateway: 2004:192:175::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
  - name: BORDERHandoff_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.179.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.179.0.0
    ipv4_gateway: 192.179.0.1
    ipv6_global_pool: 2004:192:179::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:179::0
    ipv6_gateway: 2004:192:179::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
  - name: SERVERSPOOL_sjc
    ipv6_address_space: false
    ipv4_global_pool: 192.178.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.178.0.0
    ipv4_gateway: 192.178.0.1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
  - name: SERVERSPOOL_sf
    ipv6_address_space: false
    ipv4_global_pool: 192.178.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.178.1.0
    ipv4_gateway: 192.178.1.1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
  - name: CONTRACTORS_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.182.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.182.0.0
    ipv4_gateway: 192.182.0.1
    ipv6_global_pool: 2004:192:182::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:182::0
    ipv6_gateway: 2004:192:182::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: CONTRACTORS_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.182.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.182.1.0
    ipv4_gateway: 192.182.1.1
    ipv6_global_pool: 2004:192:182::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:182::1:0
    ipv6_gateway: 2004:192:182::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: PRINTPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.176.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.176.0.0
    ipv4_gateway: 192.176.0.1
    ipv6_global_pool: 2004:192:176::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:176::0
    ipv6_gateway: 2004:192:176::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: PRINTPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.176.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.176.1.0
    ipv4_gateway: 192.176.1.1
    ipv6_global_pool: 2004:192:176::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:176::1:0
    ipv6_gateway: 2004:192:176::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: GUESTWIFIPOOL_sjc
    ipv6_address_space: true
    ipv4_global_pool: 192.180.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.180.0.0
    ipv4_gateway: 192.180.0.1
    ipv6_global_pool: 2004:192:180::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:180::0
    ipv6_gateway: 2004:192:180::1
    site_name: Global/USA/SAN JOSE
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
  - name: GUESTWIFIPOOL_sf
    ipv6_address_space: true
    ipv4_global_pool: 192.180.0.0/16
    ipv4_prefix: true
    ipv4_prefix_length: 24
    ipv4_subnet: 192.180.1.0
    ipv4_gateway: 192.180.1.1
    ipv6_global_pool: 2004:192:180::/64
    ipv6_prefix: true
    ipv6_prefix_length: 112
    ipv6_subnet: 2004:192:180::1:0
    ipv6_gateway: 2004:192:180::1:1
    site_name: Global/USA/SAN-FRANCISCO
    slaac_support: false
    pool_type: Generic
    ipv4_dhcp_servers:
    - 204.192.3.40
    ipv4_dns_servers:
    - 204.192.3.40
    ipv6_dhcp_servers:
    - 2004:192:3::40
    ipv6_dns_servers:
    - 2006:1:1::1
