---
catalyst_center_hosts:
  hosts:
    catalyst_center53:
      #catalyst_center_password: "C1sco#123!"
      catalyst_center_password: "Maglev123"
      #catalyst_center_host: 10.195.243.53
      catalyst_center_host: 10.195.243.38
      catalyst_center_port: 443
      catalyst_center_timeout: 300
      catalyst_center_username: admin
      catalyst_center_version: 2.3.7.9
      catalyst_center_verify: false
      catalyst_center_debug: true
      catalyst_center_log_level: DEBUG
      catalyst_center_log: true
      catalyst_center_log_append: false
      catalyst_center_log_file_path: "dnac_log.log"
      catalyst_center_api_task_timeout: 1200
      # dnac_log_file_path: "../../../../catc_logs/catc_logs_10.195.243.53.log
      # device_credentials:
      #   credentials_details: #Create multiple credentials for the same protocol
      #   - global_credential_details: #Create global credentials for the device list
      #       cli_credential: #Create CLI credentials list
      #       - description: CLI Sample 1
      #         username: cli-1
      #         password: "5!meh"
      #         enable_password: "q4^t^"
      #       - description: CLI2
      #         username: cli-2
      #         password: "sbs2@"
      #         enable_password: "8b!rn"
      #       - description: switchandwlc credentials
      #         username: wlcaccess
      #         password: "Lablab#123"
      #         enable_password: "Cisco#123"
      #       snmp_v3: #Create SNMPv3 credentials list
      #       - description: snmpV3 Sample 1 
      #         auth_password: "hp!x6px&#@2xi5"
      #         auth_type: SHA
      #         snmp_mode: AUTHPRIV
      #         privacy_password: "ai7tpci3j@*j5g"
      #         privacy_type: AES128
      #         username: admin
      #       https_read: #Create HTTPS Read credentials list
      #       - description: httpsRead Sample 1
      #         username: admin
      #         password: "2!x88yvqz*7"
      #         port: 443
      #       https_write: #Create HTTPS Write credentials list
      #       - description: httpsWrite Sample 1
      #         username: admin
      #         password: "j@5wgm%s2g%"
      #         port: 443
      #   ise_radius_integration_details:
      #     - authentication_policy_server:
      #       - server_type: AAA
      #         server_ip_address: 10.0.0.1
      #         shared_secret: "12345"
      #         protocol: RADIUS_TACACS
      #         authentication_port: 1812
      #         accounting_port: 1813
      #         retries: 3
      #         timeout: 4
      #         role: secondary
      #       - server_type: ISE
      #         server_ip_address: 10.195.243.59
      #         shared_secret: "Lablab#123"
      #         protocol: RADIUS_TACACS
      #         # encryption_scheme: KEYWRAP
      #         # encryption_key: "1234567890123456"
      #         # message_authenticator_code_key: asdfghjklasdfghjklas
      #         authentication_port: 1812
      #         accounting_port: 1813
      #         retries: 3
      #         timeout: 4
      #         role: primary
      #         use_dnac_cert_for_pxgrid: false
      #         pxgrid_enabled: true
      #         cisco_ise_dtos:
      #           - user_name: admin
      #             password: "Lablab#123"
      #             fqdn: ISE3-1.cisco.com
      #             ip_address: 10.195.243.59
      #             description: Cisco ISE
      #         trusted_server: true
      #         ise_integration_wait_time: 20