---
catalyst_center_hosts:
    hosts:
        catalyst_center53:
            dnac_password: Maglev123
            dnac_host: 10.195.243.53
            dnac_port: 443
            dnac_timeout: 60
            dnac_username: admin
            dnac_verify: false
            dnac_version: 2.3.7.6
            dnac_debug: true
            dnac_log_level: DEBUG
            dnac_log: true
            ansible_python_interpreter: /Users/pawansi/python3env/bin/python3.11
